title: Visualizations
modelClass: Pbs\Campaign\Models\Visualization
list: $/pbs/campaign/models/visualization/columns.yaml
recordUrl: null
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    # search:
    #    prompt: backend::lang.list.search_prompt
filter: config_filter.yaml
