# ===================================
#  List Behavior Config
# ===================================

title: Manage Campaigns
list: $/pbs/campaign/models/campaign/columns.yaml
modelClass: Pbs\Campaign\Models\Campaign
recordUrl: pbs/campaign/campaigns/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt