# ===================================
#  Form Behavior Config
# ===================================

name: Campaign
form: $/pbs/campaign/models/campaign/fields.yaml
modelClass: Pbs\Campaign\Models\Campaign
defaultRedirect: pbs/campaign/campaigns

create:
    title: Create Campaign
    redirect: pbs/campaign/campaigns/update/:id
    redirectClose: pbs/campaign/campaigns

update:
    title: Edit Campaign
    redirect: pbs/campaign/campaigns
    redirectClose: pbs/campaign/campaigns